autodetect: true
doc-warnings: true
ignore-paths: 
  - docs
  - mypackage/vendor
ignore-patterns: 
  - ^example/doc_.*\.py$
  - (^|/)docs(/|$)
max-line-length: 120
requirements: 
  - deps/core.txt
  - deps/test.txt
strictness: veryhigh
test-warnings: false
uses: 
  - django
  - celery
